### ISSUE TITLE
mysql tablelist error

### ISSUE THREAD

**Issue by lemei20002** [swida/mysqld-gdb#1]
(gdb) p select_lex->table_list 
$3 = {elements = 1, first = 0x7fff4401cb88, next = 0x7fff4401cb88}
(gdb) mysql tablelist select_lex->table_list
Python Exception <class 'gdb.error'> Attempt to take contents of a non-pointer value.: 
Error occurred in Python command: Attempt to take contents of a non-pointer value.

**Comment by swida** [comment]
command "mysql tablelist" supports TABLE_LIST struct, not SQL_I_List.  Try select_lex->leaf_tables.
